/// Credit: This code was generated by ChatGPT and Cline with DeepSeekAI Model.
"use client";
import React, { useState } from "react";
import { useForm, useFieldArray } from "react-hook-form";
import { useTranslations } from "next-intl";
import { Input } from "@/components/shadcn/input";
import { Textarea } from "@/components/shadcn/textarea";
import { Button } from "@/components/shadcn/button";
import { Label } from "@/components/shadcn/label";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/shadcn/select";

/* ========================== CONFIG DATA ========================== */

const TRACK_OPTIONS = [
  { value: "ai", label: "AI" },
  { value: "health", label: "Health" },
  { value: "env", label: "Environment" },
];

const UNIVERSITY_OPTIONS = [
  { value: "kau", label: "King Abdulaziz University" },
  { value: "other", label: "Other" },
];

const MEMBER_FIELDS = [
  {
    name: "nameAr",
    labelKey: "nameAr",
    placeholderKey: "nameAr",
    required: true,
  },
  {
    name: "nameEn",
    labelKey: "nameEn",
    placeholderKey: "nameEn",
    required: true,
  },
  { name: "phone", labelKey: "phone", placeholderKey: "phone", required: true },
  { name: "email", labelKey: "email", placeholderKey: "email", required: true },
  { name: "major", labelKey: "major", placeholderKey: "major", required: true },
];

const GENDER_OPTIONS = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];

/* ========================== FORM HOOKS & HELPERS ========================== */

// Custom hook for form logic
function useApplyForm() {
  const t = useTranslations("form");

  const form = useForm({
    mode: "onChange",
    defaultValues: {
      teamName: "",
      track: "",
      ideaTitle: "",
      ideaDescription: "",
      attachment: null,
      members: [
        {
          nameAr: "",
          nameEn: "",
          gender: "",
          phone: "",
          email: "",
          university: "",
          uniId: "",
          major: "",
          otherUniversity: "",
          isLeader: true, // First member is leader by default
        },
      ],
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "members",
  });
  const watchMembers = form.watch("members");
  const watchAttachment = form.watch("attachment");

  return { t, form, fields, append, remove, watchMembers, watchAttachment };
}

// Helper functions
function createHelpers(form) {
  const { errors, dirtyFields } = form.formState;

  const getBorderClass = (path) => {
    const parts = path.split(".");
    let error = errors;
    let dirty = dirtyFields;
    let value = form.watch();

    for (const part of parts) {
      error = error?.[part];
      dirty = dirty?.[part];
      value = value?.[part];
    }

    if (error) return "border-red-500";
    if (dirty && value && value.toString().trim() !== "")
      return "border-green-500";
    return "";
  };

  const getDirection = (value) => {
    if (!value) return "ltr";
    const first = value.trim()[0];
    return /[\u0600-\u06FF]/.test(first) ? "rtl" : "ltr";
  };

  const ErrorMessage = ({ message }) => (
    <div className="min-h-[1.25rem]">
      {message && <p className="text-red-500 text-sm mt-1">{message}</p>}
    </div>
  );

  return { getBorderClass, getDirection, ErrorMessage };
}

/* ========================== FORM SECTIONS ========================== */

// Hackathon Info Section
function HackathonInfoSection({ t, form, helpers }) {
  const { register, setValue, watch } = form;
  const { getBorderClass, ErrorMessage } = helpers;

  return (
    <div className="bg-white rounded-3xl p-6 shadow-[0_0_20px_rgba(255,255,255,0.5)]">
      <h2 className="text-3xl font-semibold text-primary mb-5">
        {t("hackathonInfo")}
      </h2>

      <div className="grid gap-5 md:grid-cols-2">
        {/* Team Name */}
        <div>
          <Label className="mb-2">{t("teamName")}</Label>
          <Input
            className={getBorderClass("teamName")}
            {...register("teamName", { required: t("errors.required") })}
            placeholder={t("placeholders.teamName")}
          />
          <ErrorMessage message={form.formState.errors.teamName?.message} />
        </div>

        {/* Track */}
        <div>
          <Label className="mb-2">{t("track")}</Label>
          <Select
            onValueChange={(value) =>
              setValue("track", value, { shouldDirty: true })
            }
          >
            <SelectTrigger
              className={`w-full ${
                form.formState.errors.track
                  ? "border-red-500"
                  : watch("track")
                  ? "border-green-500"
                  : ""
              }`}
            >
              <SelectValue placeholder={t("placeholders.track")} />
            </SelectTrigger>
            <SelectContent>
              {TRACK_OPTIONS.map((track) => (
                <SelectItem key={track.value} value={track.value}>
                  {track.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <ErrorMessage message={form.formState.errors.track?.message} />
        </div>
      </div>

      {/* Idea Section */}
      <div className="grid gap-5 mt-5">
        <div>
          <Label className="mb-2">{t("ideaTitle")}</Label>
          <Input
            className={getBorderClass("ideaTitle")}
            {...register("ideaTitle", { required: t("errors.required") })}
            placeholder={t("placeholders.ideaTitle")}
          />
          <ErrorMessage message={form.formState.errors.ideaTitle?.message} />
        </div>

        <div>
          <Label className="mb-2">{t("ideaDescription")}</Label>
          <Textarea
            className={getBorderClass("ideaDescription")}
            {...register("ideaDescription", {
              required: t("errors.required"),
              minLength: { value: 20, message: t("errors.minLength") },
            })}
            placeholder={t("placeholders.ideaDescription")}
            rows={5}
          />
          <ErrorMessage
            message={form.formState.errors.ideaDescription?.message}
          />
        </div>

        {/* Attachment */}
        <div>
          <Label className="mb-2">{t("attachment")}</Label>
          <Input
            type="file"
            accept=".pdf"
            className={`${
              form.formState.errors.attachment
                ? "border-red-500"
                : form.watch("attachment")?.length
                ? "border-green-500"
                : ""
            }`}
            {...register("attachment", {
              required: t("errors.required"),
              validate: (value) => {
                const file = value?.[0];
                if (!file) return true;
                if (file.type !== "application/pdf") return t("errors.pdfOnly");
                if (file.size > 100 * 1024 * 1024) return t("errors.pdfSize");
                return true;
              },
            })}
          />
          <ErrorMessage message={form.formState.errors.attachment?.message} />
        </div>
      </div>
    </div>
  );
}

// Member Form Section
function MemberFormSection({ member, index, t, form, helpers, onRemove }) {
  const { register, setValue, watch } = form;
  const { getBorderClass, getDirection, ErrorMessage } = helpers;
  const uniValue = form.watch(`members.${index}.university`);
  const allMembers = form.watch("members");

  const handleLeaderChange = (isLeader) => {
    // If setting this member as leader, unset all others
    if (isLeader) {
      allMembers.forEach((_, i) => {
        if (i !== index) {
          setValue(`members.${i}.isLeader`, false);
        }
      });
    }
    setValue(`members.${index}.isLeader`, isLeader);
  };

  return (
    <div className="border border-gray-200 rounded-xl p-4 mb-5">
      <div className="flex justify-between items-center mb-4">
        <h3 className="font-bold text-lg text-primary">
          {t("member")} {index + 1}
        </h3>

        {/* Team Leader Selection */}
        <div className="flex items-center gap-2">
          <Label
            htmlFor={`leader-${index}`}
            className="text-sm font-medium mb-2"
          >
            {t("teamLeader")}
          </Label>
          <Input
            type="radio"
            id={`leader-${index}`}
            checked={form.watch(`members.${index}.isLeader`)}
            onChange={(e) => handleLeaderChange(e.target.checked)}
            className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 focus:ring-blue-500"
          />
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        {MEMBER_FIELDS.map(({ name, labelKey, placeholderKey, required }) => (
          <div key={name}>
            <Label className="mb-2">{t(labelKey)}</Label>
            <Input
              dir={getDirection(form.watch(`members.${index}.${name}`))}
              className={getBorderClass(`members.${index}.${name}`)}
              {...register(`members.${index}.${name}`, {
                required: required ? t("errors.required") : false,
                ...(name === "email" && {
                  pattern: {
                    value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                    message: t("errors.email"),
                  },
                }),
                ...(name === "phone" && {
                  pattern: {
                    value: /^9665\d{8}$/,
                    message: t("errors.phoneFormat"),
                  },
                }),
              })}
              placeholder={t(`placeholders.${placeholderKey}`)}
            />
            <ErrorMessage
              message={form.formState.errors.members?.[index]?.[name]?.message}
            />
          </div>
        ))}

        {/* Gender */}
        <div>
          <Label className="mb-2">{t("gender")}</Label>
          <Select
            onValueChange={(value) =>
              setValue(`members.${index}.gender`, value, {
                shouldDirty: true,
              })
            }
          >
            <SelectTrigger
              className={`w-full ${
                form.formState.errors.members?.[index]?.gender
                  ? "border-red-500"
                  : form.watch(`members.${index}.gender`)
                  ? "border-green-500"
                  : ""
              }`}
            >
              <SelectValue placeholder="Select gender" />
            </SelectTrigger>
            <SelectContent>
              {GENDER_OPTIONS.map((gender) => (
                <SelectItem key={gender.value} value={gender.value}>
                  {gender.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <ErrorMessage
            message={form.formState.errors.members?.[index]?.gender?.message}
          />
        </div>

        {/* University */}
        <div>
          <Label className="mb-2">{t("university")}</Label>
          <Select
            onValueChange={(value) =>
              setValue(`members.${index}.university`, value, {
                shouldDirty: true,
              })
            }
          >
            <SelectTrigger
              className={`w-full ${
                form.formState.errors.members?.[index]?.university
                  ? "border-red-500"
                  : form.watch(`members.${index}.university`)
                  ? "border-green-500"
                  : ""
              }`}
            >
              <SelectValue placeholder={t("placeholders.university")} />
            </SelectTrigger>
            <SelectContent>
              {UNIVERSITY_OPTIONS.map((u) => (
                <SelectItem key={u.value} value={u.value}>
                  {u.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <ErrorMessage
            message={
              form.formState.errors.members?.[index]?.university?.message
            }
          />
        </div>

        {/* Student ID if KAU */}
        {uniValue === "kau" && (
          <div>
            <Label className="mb-2">{t("uniId")}</Label>
            <Input
              className={getBorderClass(`members.${index}.uniId`)}
              {...register(`members.${index}.uniId`, {
                required: t("errors.required"),
                pattern: {
                  value: /^[0-9]+$/,
                  message: t("errors.numericOnly"),
                },
              })}
              placeholder="1111111"
            />
            <ErrorMessage
              message={form.formState.errors.members?.[index]?.uniId?.message}
            />
          </div>
        )}

        {/* University Name if Other */}
        {uniValue === "other" && (
          <div>
            <Label className="mb-2">{t("otherUniversity")}</Label>
            <Input
              className={getBorderClass(`members.${index}.otherUniversity`)}
              {...register(`members.${index}.otherUniversity`, {
                required: t("errors.required"),
              })}
              placeholder={t("placeholders.otherUniversity")}
            />
            <ErrorMessage
              message={
                form.formState.errors.members?.[index]?.otherUniversity?.message
              }
            />
          </div>
        )}
      </div>

      {onRemove && (
        <Button
          type="button"
          onClick={onRemove}
          variant="destructive"
          className="mt-4"
        >
          {t("removeMember")}
        </Button>
      )}
    </div>
  );
}

// Team Information Section
function TeamInfoSection({ t, form, fields, append, remove, helpers }) {
  return (
    <div className="bg-white rounded-3xl p-6 shadow-[0_0_20px_rgba(255,255,255,0.5)]">
      <h2 className="text-3xl font-semibold text-primary mb-5">
        {t("teamInfo")}
      </h2>

      {fields.map((field, index) => (
        <MemberFormSection
          key={field.id}
          member={field}
          index={index}
          t={t}
          form={form}
          helpers={helpers}
          onRemove={fields.length > 1 ? () => remove(index) : null}
        />
      ))}

      {/* ADD MEMBER BUTTON */}
      {fields.length < 5 && (
        <Button
          type="button"
          onClick={() => {
            append({
              nameAr: "",
              nameEn: "",
              gender: "",
              phone: "",
              email: "",
              university: "",
              uniId: "",
              major: "",
              otherUniversity: "",
              isLeader: false, // New members are not leaders by default
            });
          }}
          className="bg-[#0EA59D] text-white font-semibold hover:opacity-90 transition-all"
        >
          + {t("addMember")}
        </Button>
      )}
    </div>
  );
}

/* ========================== MAIN COMPONENT ========================== */

export default function ApplyPage() {
  const { t, form, fields, append, remove, watchMembers, watchAttachment } =
    useApplyForm();
  const helpers = createHelpers(form);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const onSubmit = async (formData) => {
    setIsSubmitting(true);
    try {
      // Validate that exactly one member is selected as leader
      const leaders = formData.members.filter((member) => member.isLeader);
      if (leaders.length !== 1) {
        alert(t("errors.oneLeaderRequired"));
        setIsSubmitting(false);
        return;
      }

      // Create FormData for file upload
      const submitFormData = new FormData();

      // Add form fields
      submitFormData.append("teamName", formData.teamName);
      submitFormData.append("track", formData.track);
      submitFormData.append("ideaTitle", formData.ideaTitle);
      submitFormData.append("ideaDescription", formData.ideaDescription);

      // Add members as JSON string
      submitFormData.append("members", JSON.stringify(formData.members));

      // Add file if exists
      if (formData.attachment && formData.attachment.length > 0) {
        submitFormData.append("attachment", formData.attachment[0]);
      }

      console.log("📤 Submitting form data with file...");

      // Submit to API with FormData (no headers needed for FormData)
      const response = await fetch("/api/applications/submit", {
        method: "POST",
        body: submitFormData,
      });

      const result = await response.json();

      if (response.ok) {
        console.log("✅ Application submitted successfully:", result);
        alert(t("submitSuccess"));
        form.reset(); // Reset form on success
      } else {
        console.error("❌ API Error:", result);
        alert(result.error || t("errors.submissionFailed"));
      }
    } catch (error) {
      console.error("❌ Submission error:", error);
      alert(t("errors.submissionFailed"));
    } finally {
      setIsSubmitting(false);
    }
  };

  /* ========================== RENDER ========================== */

  return (
    <div className="flex flex-col gap-10 bg-gradient-to-b from-[#0F0723] via-[#3B1C89] to-[#0EA5E9] min-h-screen">
      <div className="container w-full max-w-5xl p-10 mx-auto flex flex-col gap-10">
        <h1 className="text-5xl md:text-7xl font-bold text-white text-center">
          {t("title")}
        </h1>

        <form
          onSubmit={form.handleSubmit(onSubmit)}
          className="flex flex-col gap-10"
        >
          <HackathonInfoSection t={t} form={form} helpers={helpers} />

          <TeamInfoSection
            t={t}
            form={form}
            fields={fields}
            append={append}
            remove={remove}
            helpers={helpers}
          />

          <Button
            type="submit"
            size="lg"
            disabled={isSubmitting}
            className="self-center bg-black text-white w-full text-2xl font-bold hover:scale-95 transition-transform max-w-md disabled:opacity-50"
          >
            {isSubmitting ? t("submitting") : t("submit")}
          </Button>
        </form>
      </div>
    </div>
  );
}
